// Tile asset pipeline: organizes the flat Environment tileset into grouped
// category folders, collapses the 4 directional rotations (_E/_N/_S/_W) of each
// tile into a single logical tile, and emits a typed manifest.
//
// Run with: npm run tiles
//
// All tiles share the same iso cell geometry (ground diamond centred, anchor
// ~78% down) so no per-tile image decoding is needed here — categorisation and
// flags come from the filename prefix.

import { readdirSync, statSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

// WebP output: lossy RGB with crisp alpha — far smaller than PNG, no visible
// loss on this art. Source PNGs in assets/ stay the source of truth.
const WEBP = { quality: 90, alphaQuality: 100, effort: 4 };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "assets", "Fantasy tileset - 2D Isometric V1.1", "Fantasy tileset - 2D Isometric", "Environment");
const OUT = join(ROOT, "public", "tiles");
const MANIFEST = join(ROOT, "src", "game", "tileManifest.generated.ts");

const isDir = (p) => { try { return statSync(p).isDirectory(); } catch { return false; } };
if (!isDir(SRC)) { console.error(`Source not found: ${SRC}`); process.exit(1); }

/** Map a tile's filename prefix (first word) to a category + gameplay flags. */
function classify(prefix) {
  switch (prefix) {
    case "Ground": case "BLACK":
      return { category: "floor", layer: "floor", solid: false };
    case "Wall": case "WallFlora":
      return { category: "wall", layer: "wall", solid: true };
    case "Roof":
      return { category: "roof", layer: "roof", solid: false };
    case "Tree": case "TreeTrunkBroken": case "Flora": case "Stone":
      return { category: "nature", layer: "object", solid: true };
    case "Door":
      return { category: "interactable", layer: "object", solid: true, interactable: "door" };
    case "Chest":
      return { category: "interactable", layer: "object", solid: true, interactable: "chest" };
    default:
      return { category: "prop", layer: "object", solid: false };
  }
}

const DIR_RE = /^(.*)_([NESW])$/;

rmSync(OUT, { recursive: true, force: true });

const files = readdirSync(SRC).filter((f) => f.toLowerCase().endsWith(".png")).sort();
/** id -> { category, layer, solid, interactable?, rotations: {dir: relPath} } */
const tiles = {};

for (const file of files) {
  const base = file.replace(/\.png$/i, "");
  const m = base.match(DIR_RE);
  const id = m ? m[1] : base; // collapse rotations to one tile id
  const dir = m ? m[2] : "N"; // non-directional tiles get a single 'N' slot

  const prefix = id.split(/[ _]/)[0];
  const info = classify(prefix);

  // Convert into a category subfolder as WebP.
  const outDir = join(OUT, info.category);
  mkdirSync(outDir, { recursive: true });
  const webpFile = file.replace(/\.png$/i, ".webp");
  await sharp(join(SRC, file)).webp(WEBP).toFile(join(outDir, webpFile));

  if (!tiles[id]) {
    tiles[id] = {
      id,
      category: info.category,
      layer: info.layer,
      solid: info.solid,
      ...(info.interactable ? { interactable: info.interactable } : {}),
      rotations: {},
    };
  }
  tiles[id].rotations[dir] = `${info.category}/${webpFile}`;
}

// category -> sorted tile ids
const categories = {};
for (const t of Object.values(tiles)) {
  (categories[t.category] ??= []).push(t.id);
}
for (const k of Object.keys(categories)) categories[k].sort();

const CATEGORY_ORDER = ["floor", "wall", "roof", "nature", "interactable", "prop"];
const orderedCats = {};
for (const c of CATEGORY_ORDER) if (categories[c]) orderedCats[c] = categories[c];

const banner = "// AUTO-GENERATED by scripts/build-tiles.mjs — do not edit by hand.\n\n";
const types =
  "export type TileLayer = 'floor' | 'wall' | 'roof' | 'object';\n" +
  "export type Rot = 'N' | 'E' | 'S' | 'W';\n" +
  "export interface TileDef {\n" +
  "  id: string;\n  category: string;\n  layer: TileLayer;\n  solid: boolean;\n" +
  "  interactable?: 'door' | 'chest';\n" +
  "  /** rotation -> file path under /tiles/ */\n  rotations: Partial<Record<Rot, string>>;\n}\n\n";
const body =
  "export const TILES: Record<string, TileDef> = " + JSON.stringify(tiles, null, 2) + ";\n\n" +
  "export const TILE_CATEGORIES: Record<string, string[]> = " + JSON.stringify(orderedCats, null, 2) + ";\n";

mkdirSync(dirname(MANIFEST), { recursive: true });
writeFileSync(MANIFEST, banner + types + body);

const total = Object.keys(tiles).length;
console.log(`Copied ${files.length} files into public/tiles/<category>/`);
for (const c of CATEGORY_ORDER) {
  if (categories[c]) console.log(`  ${c.padEnd(13)} ${categories[c].length} tiles`);
}
console.log(`Wrote ${total} tiles -> ${MANIFEST}`);
