// Asset pipeline: mirrors `assets/Character Sheets/<id>/<Sheet>.png` into
// `public/characters/<id>/` (what Vite serves) and scans every sheet to emit a
// typed manifest of per-animation frame counts + a per-character ground anchor.
//
// Run with: npm run sheets   (re-run whenever you add/replace character art)
//
// Why this exists: the pack's sheets are a uniform 8x15x128 grid, but some
// animations leave the last column blank (14 frames, not 15) and it varies by
// character — so frame counts must be detected, not hardcoded.

import { readdirSync, statSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { PNG } from "pngjs";
import sharp from "sharp";

// WebP output: lossy RGB (great for these HD/gradient sprites) with crisp alpha.
const WEBP = { quality: 90, alphaQuality: 100, effort: 4 };

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const SRC = join(ASSETS, "Character Sheets");
const OUT = join(ROOT, "public", "characters");
const MANIFEST = join(ROOT, "src", "game", "sheetManifest.generated.ts");

const PROJ_OUT = join(ROOT, "public", "projectiles");
const PROJ_MANIFEST = join(ROOT, "src", "game", "projectileManifest.generated.ts");

const CELL = 128;
const COLS = 15;
const ROWS = 8;
const ALPHA = 20; // opacity threshold for "this pixel has content"

const isDir = (p) => { try { return statSync(p).isDirectory(); } catch { return false; } };

/** Count populated columns by scanning row 0's band (rows are consistent). */
function frameCount(png) {
  let frames = 0;
  for (let col = 0; col < COLS; col++) {
    let any = false;
    for (let y = 0; y < CELL && !any; y++) {
      for (let x = col * CELL; x < col * CELL + CELL; x++) {
        if (png.data[(y * png.width + x) * 4 + 3] > ALPHA) { any = true; break; }
      }
    }
    if (any) frames++;
  }
  return frames;
}

/** Lowest opaque pixel within a cell, as a 0..1 fraction (1 = cell bottom). */
function anchorFraction(png) {
  let maxLocalY = 0;
  for (let y = 0; y < png.height; y++) {
    const localY = y % CELL;
    if (localY <= maxLocalY) continue;
    for (let x = 0; x < png.width; x++) {
      if (png.data[(y * png.width + x) * 4 + 3] > ALPHA) { maxLocalY = localY; break; }
    }
  }
  return (maxLocalY + 1) / CELL;
}

if (!isDir(SRC)) {
  console.error(`Source not found: ${SRC}`);
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const manifest = {};
const chars = readdirSync(SRC).filter((d) => isDir(join(SRC, d))).sort();

for (const id of chars) {
  const charSrc = join(SRC, id);
  const charOut = join(OUT, id);
  mkdirSync(charOut, { recursive: true });

  const sheets = {};
  let anchor = 0.92; // sane default if Idle is somehow missing
  const files = readdirSync(charSrc).filter((f) => f.toLowerCase().endsWith(".png"));

  for (const file of files) {
    const name = file.replace(/\.png$/i, "");
    await sharp(join(charSrc, file)).webp(WEBP).toFile(join(charOut, name + ".webp"));
    const png = PNG.sync.read(readFileSync(join(charSrc, file)));
    if (png.width !== COLS * CELL || png.height !== ROWS * CELL) {
      console.warn(`  ! ${id}/${file} is ${png.width}x${png.height}, expected ${COLS * CELL}x${ROWS * CELL}`);
    }
    sheets[name] = { frames: frameCount(png) };
    if (name === "Idle") anchor = anchorFraction(png);
  }

  manifest[id] = { anchor: Number(anchor.toFixed(4)), sheets };
  console.log(`  ${id}: ${files.length} sheets, anchor ${manifest[id].anchor}`);
}

const banner = "// AUTO-GENERATED by scripts/build-sheets.mjs — do not edit by hand.\n";
const types =
  "export interface SheetMeta { frames: number; }\n" +
  "export interface CharMeta { anchor: number; sheets: Record<string, SheetMeta>; }\n";
const body =
  "export const SHEET_MANIFEST: Record<string, CharMeta> = " +
  JSON.stringify(manifest, null, 2) +
  ";\n";

mkdirSync(dirname(MANIFEST), { recursive: true });
writeFileSync(MANIFEST, banner + types + "\n" + body);
console.log(`\nWrote ${Object.keys(manifest).length} characters -> ${MANIFEST}`);

// --- Projectiles --------------------------------------------------------
// Loose frame sequences (0001.png, 0003.png, ...) under category subfolders.
// We flatten them to public/projectiles/<Type>/ and record frame numbers + size.
const projRoot = readdirSync(ASSETS).find((d) => /^projectiles/i.test(d) && isDir(join(ASSETS, d)));
if (projRoot) {
  rmSync(PROJ_OUT, { recursive: true, force: true });
  mkdirSync(PROJ_OUT, { recursive: true });
  const projManifest = {};
  const base = join(ASSETS, projRoot);

  for (const category of readdirSync(base).filter((d) => isDir(join(base, d)))) {
    for (const type of readdirSync(join(base, category)).filter((d) => isDir(join(base, category, d)))) {
      const typeSrc = join(base, category, type);
      const typeOut = join(PROJ_OUT, type);
      mkdirSync(typeOut, { recursive: true });

      const files = readdirSync(typeSrc).filter((f) => /\.png$/i.test(f)).sort();
      const frames = [];
      const opaque = [];
      let first = null;
      for (const f of files) {
        await sharp(join(typeSrc, f)).webp(WEBP).toFile(join(typeOut, f.replace(/\.png$/i, ".webp")));
        const n = parseInt(f, 10);
        if (Number.isNaN(n)) continue;
        frames.push(n);
        const png = PNG.sync.read(readFileSync(join(typeSrc, f)));
        if (!first) first = png;
        let count = 0;
        for (let i = 3; i < png.data.length; i += 4) if (png.data[i] > ALPHA) count++;
        opaque.push(count);
      }
      // Skip near-empty intro frames (e.g. an arrow being nocked) so a looping
      // projectile doesn't flicker invisible.
      const maxOp = Math.max(...opaque, 1);
      let start = opaque.findIndex((o) => o >= maxOp * 0.25);
      if (start < 0) start = 0;
      projManifest[type] = { category, frames, start, w: first.width, h: first.height };
      console.log(`  proj ${type}: ${frames.length} frames (start ${start}), ${first.width}x${first.height}`);
    }
  }

  const projTypes = "export type ProjectileType = " +
    Object.keys(projManifest).map((t) => `"${t}"`).join(" | ") + ";\n";
  const projType =
    "export interface ProjectileMeta { category: string; frames: number[]; start: number; w: number; h: number; }\n";
  const projBody =
    "export const PROJECTILE_MANIFEST: Record<ProjectileType, ProjectileMeta> = " +
    JSON.stringify(projManifest, null, 2) + ";\n";
  mkdirSync(dirname(PROJ_MANIFEST), { recursive: true });
  writeFileSync(PROJ_MANIFEST, banner + projTypes + projType + "\n" + projBody);
  console.log(`Wrote ${Object.keys(projManifest).length} projectiles -> ${PROJ_MANIFEST}`);
}
